title: scpcom
email: scpcom@users.noreply.github.com
description: >- 
  This project provides debian packages for sg200x based boards.
baseurl: ""
url: "https://scpcom.github.io"
github_username: scpcom

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/